#if !defined(_ACCOUNT_H)
#define _ACCOUNT_H
//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Final_Project_2
//  @ File Name : Account.h
//  @ Date : 25/04/2020
//  @ Author : Vy Huynh and Kim Nguyen and Arooj
//
//


#include "Customer.h"
#include <string>
#include <iostream>
#include <functional> // reference_wrapper
#include <vector>
using namespace std;
class Account
{
public:
	Account();
	Account(int newAccountId);
	Account(string newAccountPassword);
	Account(double newAccountBalance);
	Account(int newAccountId, string newAccountPassword);
	Account(int newAccountId, double newAccountBalance);
	Account(string newAccountPassword, double newAccountBalance);
	Account(int newAccountId, string newAccountPassword, double newAccountBalance);
	~Account();
	void setAccountId(int newAccountId);
	void setAccountBalance(double newAccountBalance);	
	void setAccountPassword(string newAccountPassword);
	


	int getAccountId() const;
	double getAccountBalance() const;
	string getAccountPassword() const;
	
	
private:
	int accountId;
	string accountPassword;
	double accountBalance;
	

	
};



#endif  //_ACCOUNT_H
