#if !defined(_BANK_H)
#define _BANK_H
//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Final_Project_2
//  @ File Name : Bank.h
//  @ Date : 26/04/2020
//  @ Author : Vy Huynh and Kim Nguyen and Arooj
//
//
#include <string>
#include <iostream>
#include "Account.h"
using namespace std;



class Bank {
public:
	Bank();
	Bank(string newBankName, Account newBankAccount);
	void deposit();
	void withdraw();
	void display();
	void setBankName(string newBankName);
	friend std::ostream& operator<<(std::ostream& out, const Bank& bank);
	Account getBankAccount();
	void addAccount(Account& account);
	string getBankName();
	void setBankAccount(Account newBankAccount);
	
private:
	string bankName;
	Account bankAccount;
	std::vector<std::reference_wrapper<const Account>> accountList{};
};

#endif  //_BANK_H
